# Preprocessing
---

In [ ]:
import pandas as pd

# Receive dataframe from ExploratoryAnalysis
%store -r df

# Get dummy variables as False=0 and True=1
dummy_vars = pd.get_dummies(df, dtype=int)
# Drop no categories
dummy_vars = dummy_vars.drop(["Stage_fear_No", "Drained_after_socializing_No"], axis="columns")
# Replace dataframe
df = dummy_vars
df

,Time_spent_Alone,Social_event_attendance,Going_outside,Friends_circle_size,Post_frequency,Stage_fear_Yes,Drained_after_socializing_Yes,Personality_Extrovert,Personality_Introvert
0,4.0,4.0,6.0,13.0,5.0,0,0,1,0
1,9.0,0.0,0.0,0.0,3.0,1,1,0,1
2,9.0,1.0,2.0,5.0,2.0,1,1,0,1
3,0.0,6.0,7.0,14.0,8.0,0,0,1,0
4,3.0,9.0,4.0,8.0,5.0,0,0,1,0
...,...,...,...,...,...,...,...,...,...
2895,3.0,7.0,6.0,6.0,6.0,0,0,1,0
2896,3.0,8.0,3.0,14.0,9.0,0,0,1,0
2897,4.0,1.0,1.0,4.0,0.0,1,1,0,1
2898,11.0,1.0,NaN,2.0,0.0,1,1,0,1
2899,3.0,6.0,6.0,6.0,9.0,0,0,1,0